# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET


BloggerBlogBundle_about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET


BloggerBlogBundle_contact:
    path:  /contact
    defaults: { _controller: "BloggerBlogBundle:Page:contact" }
    requirements:
        methods:  GET|POST

BloggerBlogBundle_blog:
    path:  /blog
    defaults: { _controller: "BloggerBlogBundle:Blog:blog" }
    requirements:
        methods:  GET
BloggerBlogBundle_blog_show:
    path:  /blog/{id}/{slug}
    defaults: { _controller: "BloggerBlogBundle:Blog:show", comments: true }
    requirements:
        methods:  GET
        id: \d+


BloggerBlogBundle_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: "BloggerBlogBundle:Comment:create" }
    requirements:
        methods:  POST
        blog_id: \d+


BloggerBlogBundle_seo:
    path:   /seo-prodvizhenie-sajta
    defaults: { _controller: "BloggerBlogBundle:Page:seo" }
    requirements:
    methods:  GET|POST

BloggerBlogBundle_create:
    path:   /create-new-site
    defaults: { _controller: "BloggerBlogBundle:Page:create" }
    requirements:
    methods:  GET

BloggerBlogBundle_support:
    path:   /support-site
    defaults: { _controller: "BloggerBlogBundle:Page:support" }
    requirements:
    methods:  GET

BloggerBlogBundle_programmer:
    path:   /programmer
    defaults: { _controller: "BloggerBlogBundle:Page:programmer" }
    requirements:
    methods:  GET

BloggerBlogBundle_projects:
    path:   /projects
    defaults: { _controller: "BloggerBlogBundle:Page:projects" }
    requirements:
    methods:  GET

BloggerBlogBundle_confirm:
    path:   /confirm
    defaults: { _controller: "BloggerBlogBundle:Page:confirm" }
    requirements:
    methods:  GET|POST

BloggerBlogBundle_seoyandex:
    path:   /seo-prodvizhenie-sajta/prodvizhenie-sajta-v-yandex
    defaults: { _controller: "BloggerBlogBundle:Page:seoyandex" }
    requirements:
    methods:  GET|POST

BloggerBlogBundle_websajti:
    path:   /seo-prodvizhenie-sajta/prodvizhenie-web-sajtov
    defaults: { _controller: "BloggerBlogBundle:Page:websajti" }
    requirements:
    methods:  GET|POST

BloggerBlogBundle_priceseo:
    path:   /seo-prodvizhenie-sajta/ceny-na-prodvizhenie-sajta
    defaults: { _controller: "BloggerBlogBundle:Page:priceseo" }
    requirements:
    methods:  GET|POST

BloggerBlogBundle_seotopten:
    path:   /seo-prodvizhenie-sajta/prodvizhenie-sajtov-v-top-10
    defaults: { _controller: "BloggerBlogBundle:Page:seotopten" }
    requirements:
    methods:  GET|POST

